/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_velo_rdb_RedisCrc */

#ifndef _Included_io_velo_rdb_RedisCrc
#define _Included_io_velo_rdb_RedisCrc
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     io_velo_rdb_RedisCrc
     * Method:    crc64Init
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_io_velo_rdb_RedisCrc_crc64Init
      (JNIEnv *, jclass);

    /*
     * Class:     io_velo_rdb_RedisCrc
     * Method:    crc64
     * Signature: (J[BJ)J
     */
    JNIEXPORT jlong JNICALL Java_io_velo_rdb_RedisCrc_crc64
      (JNIEnv *, jclass, jlong, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
